FROM balenalib/raspberry-pi-golang AS builder

LABEL Author=Kerberos.io

RUN apt-get update && apt-get upgrade -y && apt-get install -y wget build-essential \
    cmake libc-ares-dev uuid-dev daemon libwebsockets-dev git \
    cmake wget dh-autoreconf autotools-dev autoconf automake gcc \
    build-essential libtool make ca-certificates nasm tar unzip wget pkg-config

#############################
# Static build x264

RUN git clone https://code.videolan.org/videolan/x264.git && \
    cd x264 && git checkout 0a84d986 && \
    ./configure --prefix=/usr/local --enable-static --enable-pic && \
    make -j8 && \
    make install && \
    cd .. && rm -rf x264

#################################
# Clone and build FFMpeg & OpenCV

RUN git clone https://github.com/FFmpeg/FFmpeg && \
    cd FFmpeg && git checkout n5.0.1 && \
    ./configure --prefix=/usr/local --target-os=linux --enable-nonfree \
    --extra-ldflags="-latomic" \
    --enable-avfilter \
    --disable-zlib \
    --enable-gpl \ 
    --extra-libs=-latomic  \
    --enable-static --disable-shared  && \
    make -j8 && \
    make install && \
    cd .. && rm -rf FFmpeg

########################
# Download Yarn

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn