name: Docker amd64

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: kerberos/base:beta-amd64
    #- name: Scan
    #  uses: Azure/container-scan@v0
    #  with:
    #    image-name: kerberos/base:beta
    - name: Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kerberos/base:beta-amd64

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Merge manifest
      run: docker buildx imagetools create --append -t kerberos/base:beta kerberos/base:beta-amd64