name: Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: kerberos/base:beta
    - name: Scan
      uses: Azure/container-scan@v0
      with:
        image-name: kerberos/base:beta
    - name: Push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kerberos/base:beta
